#!/usr/bin/env bash
# Generated by ydotooler

ydotool key 29:1 #KEY_LEFTCTRL
ydotool key 56:1 #KEY_LEFTALT
ydotool key 20:1 20:0 #KEY_T
ydotool key 29:0 #KEY_LEFTCTRL
ydotool key 56:0 #KEY_LEFTALT
sleep 0.5
ydotool type "vim"
ydotool key 28:1 28:0 #KEY_ENTER
sleep 0.3
ydotool key 23:1 23:0 #KEY_I
sleep 0.3
ydotool type "Hello world!"
ydotool key 28:1 28:0 #KEY_ENTER
ydotool key 1:1 1:0 #KEY_ESC
