#!/usr/bin/env bash
# Generated by ydotooler

ydotool key 29:1 #KEY_LEFTCTRL
sleep 0.5
ydotool key 56:1 #KEY_LEFTALT
sleep 0.5
ydotool key 17:1 17:0 #KEY_W
sleep 0.5
ydotool key 29:0 #KEY_LEFTCTRL
sleep 0.5
ydotool key 56:0 #KEY_LEFTALT
sleep 0.5
sleep 2
ydotool type "vim"
sleep 0.5
ydotool key 28:1 28:0 #KEY_ENTER
sleep 0.5
sleep 1
ydotool key 23:1 23:0 #KEY_I
sleep 0.5
ydotool type "hey, this is and example"
sleep 0.5
ydotool key 28:1 28:0 #KEY_ENTER
sleep 0.5
ydotool type "this is a thing I made"
sleep 0.5
ydotool key 28:1 28:0 #KEY_ENTER
sleep 0.5
ydotool type "I am pretty happy with it"
sleep 0.5
ydotool key 28:1 28:0 #KEY_ENTER
sleep 0.5
ydotool type "I have wanted something like this since I switched to linux"
sleep 0.5
ydotool key 28:1 28:0 #KEY_ENTER
sleep 0.5
ydotool type "but I could not find anything like this"
sleep 0.5
ydotool key 28:1 28:0 #KEY_ENTER
sleep 0.5
ydotool type "so I made it"
sleep 0.5
ydotool key 57:1 57:0 #KEY_SPACE
sleep 0.5
ydotool key 42:1 #KEY_LEFTSHIFT
sleep 0.5
ydotool key 39:1 39:0 #KEY_SEMICOLON
sleep 0.5
ydotool key 42:0 #KEY_LEFTSHIFT
sleep 0.5
ydotool key 180:1 180:0 #KEY_KPRIGHTPAREN
sleep 0.5
ydotool key 28:1 28:0 #KEY_ENTER
sleep 0.5
ydotool key 1:1 1:0 #KEY_ESC
sleep 0.5
